version: '3'
services:
  nginx:
    container_name: flippin_nginx
    image: nginx:latest
    ports:
      - "18080:80"
    volumes:
      - ../api:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: flippin_php
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - ../api:/var/www/html
  mysql:
    container_name: flippin_mysql
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      MYSQL_DATABASE: flippin
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
